version: '3.8'
services:
  webapp:
    build:
      context: ./webapp
    ports:
      - "5001:5000"
    environment:
      - USE_SERVER_DB=1
    volumes:
      - ./webapp:/app
      - webapp_data:/root/.local/share/TimeTrackerWeb
    restart: unless-stopped

volumes:
  webapp_data:
